### ISSUE TITLE
Meta Issue: Jobs for Christmas 2018

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#104]
We have a few issues that need resolving over this holiday.

- [x] #67 We keep putting off the anon feedback form, but it needs doing.
- [x] #100 Need to ask for optional real name on signup to make everyone's lives easier.
- [x] #101 This tiny bug has been bugging (ha) Jakub for a while.
- [x] #102 Need to create an FAQ page (done site-side) and link to it (...not done site-side).
- [x] #103 Ares hath decreed it, or something idk.
- [x] #105 Getting image uploads to work would make my life a lot easier.

If we get time after all of that, there are many issues that we could also look at such as #88 , #91 and #87. Also we need to fix the RPG Rep permissions.
