### ISSUE TITLE
Events system overhaul!

### ISSUE THREAD

**Issue by ashbc** [the-Bruce/tgrsite#95]
Meta-issue for issues pertaining to the Events system.

Individual issues to be made and linked ad hoc when work/discussion starts.

**Bugs**
- [x] Clicking "show past games" then "show only RPGs" discards the "show past games" filter.
- [x] Filtering by tags (/events/tagged/:tag) seems to sort in reverse compared to no-filter list (/events/)
- [x] "clear filters" button inappropriately labelled as "Show all games (not just RPGs)"

**Enhancements**
- [x] Change "Games" title to "Events"
- [ ] Autocomplete for tag filter input
- [x] Show active filter(s) in list view
- [x] Add support for multi-filters?
- [x] Help text for form fields (especially "Are you running this?")
- [x] Remove "Has this finished?" from create view
- [x] Link from create page back to list ("Back"?), or make creation page part of list page
- [x] Display long player lists more neatly / truncate
- [x] Increase truncation cutoff length for event descriptions
- [x] Add pagination to list view #88 
- [x] Filter option to hide full events #66

**Comment by the-Bruce** [comment]
Pagination done in c7ba50c3972e596d2d9faf4bba01e24dff821c58

**Comment by the-Bruce** [comment]
Everything except tag autocomplete now addressed
